### ISSUE TITLE
VTB 補 

### ISSUE THREAD

**Issue by aimopanda** [simon300000/vtbs.moe#1]
https://space.bilibili.com/406548031/

**Comment by darth-zhang** [comment]
https://space.bilibili.com/420321371/
哈弟
https://space.bilibili.com/401480763/
真白花音(Chukolala)
https://space.bilibili.com/407106379/
绯赤ERIO(Chukolala)

**Comment by simon300000** [comment]
OK

**Comment by Yummy-X** [comment]
https://space.bilibili.com/5563350
https://space.bilibili.com/20530305
https://space.bilibili.com/4763529
https://space.bilibili.com/198297

**Comment by simon300000** [comment]
OK
不过前两个就是第三和第四哦→_→？

**Comment by gw15328** [comment]
https://space.bilibili.com/176486647
银河爱丽丝搬运
https://space.bilibili.com/5730
星乃めあFanClub
https://space.bilibili.com/394918929
ウタゴエ放送部粉丝会
辛苦啦~

**Comment by simon300000** [comment]
Okay→_→
不过以后还是新开issue吧，这样感觉所有人都总是会收到邮件提醒什么的不大好
