### ISSUE TITLE
感觉有必要优化一下加载速度了

### ISSUE THREAD

**Issue by wudifeixue** [simon300000/vtbs.moe#15]
由于在跟群友分享网站的时候，大家反映打开速度实在是过慢，我查了查Network也确实被这个情况惊到了。
![image](https://user-images.githubusercontent.com/7316929/58315560-02c9e980-7dcf-11e9-89ef-b3f1a6e96692.png)

居然在加载页面花掉了54.1M。虽然说多数是图片，但是挺惊人了。

  
![image](https://user-images.githubusercontent.com/7316929/58315756-5d634580-7dcf-11e9-840a-861d88a12004.png)

其他的看也还好。考虑分页图片？不然随着数据的增加，这个加载感觉会变得更夸张。

**Comment by simon300000** [comment]
我的网站加载大概有4个阶段
1. html和js
2. 连接Websocket
3. Vue渲染Websocket发来的数据
4. 加载那些VTB头像

这里看，主要是步骤4的速度有点慢了？

**Comment by wudifeixue** [comment]
看样子是的，这个明显的把51M的数据降低到5.2M左右了。

**Comment by simon300000** [comment]
问题似乎解决了→_→
那我close咯
