### ISSUE TITLE
关于转生势

### ISSUE THREAD

**Issue by Yummy-X** [simon300000/vtbs.moe#4]
OK
不过前两个就是第三和第四哦→_→？

_Originally posted by @simon300000 in https://github.com/simon300000/vtbs.moe/issues/1#issuecomment-491211291_

**Comment by simon300000** [comment]
没事哦，不用新开一个issue哦嘿嘿嘿
其实我在想，要不要加入一个虚拟血统设定→_→？
突然转生vtb，要怎么处理这样的，是不是需要特殊对待，我有点懵

**Comment by Yummy-X** [comment]
我第一次使用GitHub不太熟悉!!!∑(ﾟДﾟノ)ノ咕咩！
emmmm 转生势需要单独标注么~|ू･ω･` )
这样的话，突然想起一只巨物转生vtb，https://space.bilibili.com/282994

**Comment by simon300000** [comment]
惊了
这个人连vtb出道/自我介绍视频都木有
我都不知道怎么处理

**Comment by Yummy-X** [comment]
hhhhh，她很早之前就有虚拟形象和MMD模型了，然后突然某一天就开始用虚拟形象直播了~

**Comment by simon300000** [comment]
加吧加吧
看不到超美丽3D，就是vtb（暴言

**Comment by simon300000** [comment]
~~加吧加吧~~
~~看不到超美丽3D，就是vtb（暴言~~

这最近的视频也没有虚拟主播的感觉，还是先缓缓
