### ISSUE TITLE
关于OHLC图（K线图）

### ISSUE THREAD

**Issue by MiracleXYZ** [simon300000/vtbs.moe#6]
https://vtbs.moe/macro
好像K线图有些问题：K线图是OHLC或者OCLH（开盘、收盘、最低、最高），现在并没有「最高」的数据，却有两个「收盘」……
这可能是个bug……

**Comment by simon300000** [comment]
的确有两个收盘...
因为B站的舰长在一天内只增不减，然后到了12点会少，也就是过期的舰长
所以我
开盘=前一天结束时的舰长数
最低=今天0:00后舰长过期后->最低数
收盘=今天结束时舰长数->最高数 = 明天开盘数

所以收盘=最高。。。

**Comment by MiracleXYZ** [comment]
是这样啊……怪不得我看到K线图全是朝着一个方向的……
如果后面要做周线或者月线的话，就应该有OCLH四个值了。

**Comment by simon300000** [comment]
嗯，过段时间数据比较多了应该就能做出来了
周线图和月线图
