### ISSUE TITLE
请问会收录非官方号吗？

### ISSUE THREAD

**Issue by zhihaofans** [simon300000/vtbs.moe#9]
请问会收录非官方的搬运字幕组号吗？

**Comment by simon300000** [comment]
会
目前就有许多非官方搬运号

**Comment by zhihaofans** [comment]
> 会
> 目前就有许多非官方搬运号

那我安利一下彩虹社的`久远千岁`，2019年1月10日开始活动的，唱歌还不错，Youtube/bilibili的订阅分别是7.7万/1.9万，这个订阅数应该不少了。

- Youtube: https://www.youtube.com/channel/UCP2o-o6u4uX3uq1hXspl0rg

- Bilibili: https://space.bilibili.com/257492/

- 百科: https://zh.moegirl.org/%E4%B9%85%E8%BF%9C%E5%8D%83%E5%B2%81

**Comment by simon300000** [comment]
白发关注了关注了

**Comment by zhihaofans** [comment]
@simon300000 推荐去看她昨天的视频，1小时的唱歌

**Comment by simon300000** [comment]
嗯，谢谢推荐
我目前在看她直播→_→
